# Generated by Django 4.0.6 on 2022-08-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=270)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=270)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=270)),
                ('url', models.URLField(max_length=300)),
                ('image', models.ImageField(upload_to='project_images')),
                ('desc', models.TextField()),
            ],
        ),
    ]
